#pragma config(Motor,  motor2,          leftWheel,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          rightWheel,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main() {
	while (true) {
		motor[leftWheel] = 127;
		motor[rightWheel] = 127;
	}
}
