#pragma config(Motor,  motor1,          intake,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          leftWheel,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          leftLift,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          rightLift,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightWheel,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		motor[leftWheel] = vexRT[ChA] + vexRT[ChB];
		motor[rightWheel] = vexRT[ChA] - vexRT[ChB];
		motor[intake] = vexRT[ChD];


		if (vexRT[BtnLUp] == 1) {
			while(true) {
				if (vexRT[BtnLDown] == 1) {
					break;
					} else {
					motor[leftWheel] = vexRT[ChA] + vexRT[ChB];
					motor[rightWheel] = vexRT[ChA] - vexRT[ChB];
					motor[intake] = vexRT[ChD];

					motor[leftLift] = -63;
					motor[rightLift] = -63;

				} // Close small If
			} // Close While
		} // Close big If


		if (vexRT[BtnLDown] == 1) {
			while(true) {
				if (vexRT[BtnLUp] == 1) {
					break;
					} else {

					motor[leftWheel] = vexRT[ChA] + vexRT[ChB];
					motor[rightWheel] = vexRT[ChA] - vexRT[ChB];
					motor[intake] = vexRT[ChD];

					motor[leftLift] = 15;
					motor[rightLift] = 15;

				} // Close small If
			} // Close While
		} // Close big If


	} // Close While
} // Close Root
